### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by wanwanruwoxin** [KyleBing/diary-portal#3]
你好，能发下mysql数据库的表吗

**Comment by KyleBing** [comment]
https://github.com/KyleBing/diary-portal#4-%E5%88%9D%E5%A7%8B%E5%8C%96%E6%95%B0%E6%8D%AE%E5%BA%93


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年4月28日 10:51 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [KyleBing/diary-portal] 数据库 (Issue #3) |

你好，能发下mysql数据库的表吗
