### ISSUE TITLE
npm install和yarn addd都报错，请问该怎么解决

### ISSUE THREAD

**Issue by wanwanruwoxin** [KyleBing/diary-portal#4]
![image](https://user-images.githubusercontent.com/75788227/235043847-c9e3bda3-440b-4dec-9f41-d169e10d9b60.png)

**Comment by KyleBing** [comment]
需要 nodejs 18+


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年4月28日 10:58 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [KyleBing/diary-portal] npm install和yarn addd都报错，请问该怎么解决 (Issue #4) |
